### PR TITLE
enable testing with python 3.6 and 3.7

### PR DESCRIPTION
**Pull request by abalkin**

### CODE REVIEW

**Comment by abalkin** [comment]
It looks like travis uses ubuntu xenial that is too old to have python 3.6 and 3.7 packages.

One possible solution is to compile python from sources in CI.  With a proper caching, it should not be too expensive per build.  @pv - what do you think?

**Comment by abalkin** [comment]
Interesting.  Apparently Travis supports ubuntu:bionic, but for some reason it does not install APT packages ...

**Comment by abalkin** [comment]
This looks better, but to include python 3.5, we need to add a separate job running on ubuntu:xenial.

**Comment by pv** [comment]
You'll also need to run the pytest3,4,5 environments

**Comment by abalkin** [comment]
> You'll also need to run the pytest3,4,5 environments

I've seen those, but I could not understand what they do.  Are these for different versions of pytest?

**Comment by abalkin** [comment]
@pv - I think I did what you asked for.

**Pull request merged**
